apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: dev
type: Opaque
stringData:
  DB_USER: root
  DB_PASSWORD: password
  JWT_SECRET: "mysuperjwtsecret"
  DB_NAME: "test"
  PORT: "3000"
  DB_HOST: mysql.dev.svc.cluster.local
