apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: { { .Values.namespace } }
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: { { .Values.backend.containerPort } }
      targetPort: { { .Values.backend.containerPort } }
  type: ClusterIP
