apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: {{ .Values.frontend.containerPort }}
      targetPort: {{ .Values.frontend.targetPort }}
  type: ClusterIP
