apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: { { .Values.namespace } }
spec:
  replicas: { { .Values.frontend.replicaCount } }
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: { { .Values.frontend.image.repository } }:{ { .Values.frontend.image.tag } }
          imagePullPolicy: { { .Values.frontend.image.pullPolicy } }
          ports:
            - containerPort: { { .Values.frontend.containerPort } }
          env:
            {% for k, v in .Values.frontend.env.items() %}
            - name: { '{' } k { '}' }
              value: { '{' } v { '}' }
            {% endfor %}
          resources:
            { '{ toYaml .Values.%s.resources | nindent 12 }' % name }
          livenessProbe: { '{ toYaml .Values.%s.livenessProbe | nindent 12 }' % name }
          readinessProbe: { '{ toYaml .Values.%s.readinessProbe | nindent 12 }' % name }
