apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc-{{ .Values.namespace }}
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: mysql-pv-{{ .Values.namespace }}
  storageClassName: ""
