apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.mysql.replicaCount }}
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: {{ .Values.mysql.image.repository }}:{{ .Values.mysql.image.tag }}
          imagePullPolicy: {{ .Values.mysql.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.mysql.containerPort }}
          env:
            {{- range $key, $val := .Values.mysql.env }}
            - name: {{ $key }}
              valueFrom: {{ toYaml $val | nindent 16 }}
            {{- end }}
          resources:
            {{ toYaml .Values.mysql.resources | nindent 12 }}
          livenessProbe:
            {{ toYaml .Values.mysql.livenessProbe | nindent 12 }}
          readinessProbe:
            {{ toYaml .Values.mysql.readinessProbe | nindent 12 }}
          volumeMounts:
            {{ toYaml .Values.mysql.volumeMounts | nindent 12 }}
      volumes:
        {{ toYaml .Values.mysql.volumes | nindent 8 }}
