apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-{{ .Values.namespace }}
spec:
  capacity:
    storage: {{ .Values.mysql.storage.size }}
  accessModes:
    - {{ .Values.mysql.storage.accessMode }}
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: {{ .Values.mysql.storage.path }}
