apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  mysql-user: {{ .Values.mysql.auth.user }}
  mysql-password: {{ .Values.mysql.auth.password }}
  mysql-root-password: {{ .Values.mysql.auth.rootPassword }}
