apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: dev
type: Opaque
data:
  mysql-root-password: cGFzc3dvcmQ= # "password" en base64
  mysql-user: ZGV2dXNlcg== # "devuser"
  mysql-password: ZGV2cGFzcw== # "devpass"
