backend:
  containerPort: 3000
  env:
    DB_HOST: mysql
    NODE_ENV: production
  image:
    pullPolicy: IfNotPresent
    repository: backend
    tag: prod
  livenessProbe:
    httpGet:
      path: /test
      port: 3000
    initialDelaySeconds: 5
    periodSeconds: 10
  readinessProbe:
    httpGet:
      path: /test
      port: 3000
    initialDelaySeconds: 5
    periodSeconds: 10
  replicaCount: 3
  resources:
    limits:
      cpu: '1'
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
frontend:
  port: 80
  containerPort: 3000
  env:
    NEXT_PUBLIC_API_URL: http://backend.prod.svc.cluster.local:3000
  image:
    pullPolicy: IfNotPresent
    repository: frontend
    tag: prod
  livenessProbe:
    httpGet:
      path: /
      port: 3000
    initialDelaySeconds: 5
    periodSeconds: 10
  readinessProbe:
    httpGet:
      path: /
      port: 3000
    initialDelaySeconds: 5
    periodSeconds: 10
  replicaCount: 3
  resources:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 250m
      memory: 128Mi
ingress:
  annotations: {}
  className: nginx
  enabled: true
  hosts:
    - host: ""
      paths:
      - backend: backend
        path: /api/
        pathType: Prefix
        port: 3000
      - backend: frontend
        path: /
        pathType: Prefix
        port: 80
mysql:
  config:
    database: test
  auth:
    user: dev
    password: devpassword
    rootPassword: password
  storage:
    size: 1Gi
    accessMode: ReadWriteOnce
    path: /mnt/data/mysql
  containerPort: 3306
  env:
    MYSQL_DATABASE:
      configMapKeyRef:
        key: mysql-database
        name: mysql-config
    MYSQL_PASSWORD:
      secretKeyRef:
        key: mysql-password
        name: mysql-secret
    MYSQL_ROOT_PASSWORD:
      secretKeyRef:
        key: mysql-root-password
        name: mysql-secret
    MYSQL_USER:
      secretKeyRef:
        key: mysql-user
        name: mysql-secret
  image:
    pullPolicy: IfNotPresent
    repository: mysql
    tag: '8.0'
  livenessProbe:
    tcpSocket:
      port: 3306
    initialDelaySeconds: 5
    periodSeconds: 10
  readinessProbe:
    tcpSocket:
      port: 3306
    initialDelaySeconds: 5
    periodSeconds: 10
  replicaCount: 1
  resources:
    limits:
      cpu: '1'
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi
  volumeMounts:
    - mountPath: /var/lib/mysql
      name: mysql-storage
  volumes:
    - name: mysql-storage
      persistentVolumeClaim:
        claimName: mysql-pvc-prod
namespace: prod
